language: python

python:
- 3.7

install:
- pip install -r requirements.txt
- pip install coveralls

script:
- pycodestyle --max-line-length=99 -r *.py app/*.py
- pytest --cov 

after_success:
- coveralls
